from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.agent_toolkits import OpenAPIToolkit, create_openapi_agent
from langchain_community.agent_toolkits.openapi.spec import reduce_openapi_spec
from langchain_community.agent_toolkits.openapi import planner
from langchain_community.utilities.requests import RequestsWrapper
import readline
import requests
import yaml

llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash",temperature=0)
openapi_spec = requests.get("https://raw.githubusercontent.com/APIs-guru/unofficial_openapi_specs/master/xkcd.com/1.0.0/openapi.yaml").text
raw_api_spec = yaml.load(openapi_spec, Loader=yaml.Loader)
api_spec = reduce_openapi_spec(raw_api_spec)

xkcd_agent = planner.create_openapi_agent(
    api_spec=api_spec,
    llm=llm,
    requests_wrapper=RequestsWrapper(),
    allow_dangerous_requests=True,
)

print("Welcome to my XKCD API application. I am configured with these tools generated by the OpenAPIToolkit:")
for tool in xkcd_agent.tools:
  print(f'  Tool: {tool.name} = {tool.description}')

while True:
    line = input("llm>> ")
    if line:
        try:
            result = xkcd_agent.invoke(line)
            print(result)
        except Exception as e:
            print(e)
    else:
        break
